# Generated by Django 3.0.5 on 2021-05-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('blog_id', models.IntegerField(primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=255)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='blog_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField()),
                ('comm', models.TextField()),
            ],
        ),
    ]
